### ISSUE TITLE
gds in your test cases

### ISSUE THREAD

**Issue by danchitnis** [mabrains/sky130_klayout_pdk#24]
@mohanad0mohamed Hello, Is it possible to let me know where did you find the gds files that you have [here](https://github.com/mabrains/sky130_klayout_pdk/tree/main/sky130_tech/tech/sky130/lvs/testing/testcases/sc_testcases/hd)? I can't find these in the Skywater repository.

**Comment by mohanad0mohamed** [comment]
Hi @danchitnis 
Kindly find them in each directory [here](https://github.com/google/skywater-pdk-libs-sky130_fd_sc_hd/tree/main/cells). I have just combined them together in one directory.
Please let me know if you want any info regarding these files.

**Comment by danchitnis** [comment]
Got it! Some great works in this repository! I will try it and get back to you. Closing the issue for now.
