### ISSUE TITLE
`ERROR: invalid literal for int() with base 10: 'Connection Up' in PCellDeclaration.produce`

### ISSUE THREAD

**Issue by llandsmeer** [mabrains/sky130_klayout_pdk#4]
KLayout version 0.27.8 (fresh install)
Sky130 PDK 9d36065b2a48fc4215f26fca5a2193ea5641f7ab
Python 3.8.10
Linux 5.13.0-30-generic #33~20.04.1-Ubuntu SMP Mon Feb 7 14:25:10 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Trying to place a nmos, I get the following error (and nothing happens):

```
ERROR: invalid literal for int() with base 10: 'Connection Up' in PCellDeclaration.produce
  /home/llandsmeer/.klayout/tech/sky130/pymacros/sky130_pcells/nmos18.py:123
  :/built-in-pymacros/pcell_declaration_helper.lym:185
```

**Comment by atorkmabrains** [comment]
Thanks @llandsmeer That was fixed. Thanks to [pepijndevos](https://github.com/mabrains/sky130_klayout_pdk/issues?q=is%3Apr+author%3Apepijndevos)
